- type: split-column
  max-columns: 5
  widgets:
    - title: vaultwarden
      type: extension
      url: http://glance-restic:8675/vaultwarden
      allow-potentially-dangerous-html: true
    - title: immich
      type: extension
      url: http://glance-restic:8675/immich
      allow-potentially-dangerous-html: true
