- type: split-column
  max-columns: 5
  widgets:
    - title: vaultwarden
      type: extension
      url: http://glance-restic:8675/vaultwarden
      allow-potentially-dangerous-html: true
    - title: vaultwarden_hz
      type: extension
      url: http://glance-restic:8675/vaultwarden_hz
      allow-potentially-dangerous-html: true
    - title: syncthing
      type: extension
      url: http://glance-restic:8675/syncthing
      allow-potentially-dangerous-html: true
    - title: syncthing_hz
      type: extension
      url: http://glance-restic:8675/syncthing_hz
      allow-potentially-dangerous-html: true
